@startgantt
printscale daily zoom 4
saturday are closed
sunday are closed

Project starts the 2nd of january 2023

[Skriv user stories] as [TASK1] lasts 1 days
[TASK1] is colored in Lavender/LightBlue
[TASK1] is 100% complete

[Skriv accept tests] as [TASK2] on {Asbjørn:25%} {Nilas:25%} {Phillip:25%} {Sandie:25%} lasts 1 days
[TASK2] is colored in Lavender/LightBlue
[TASK2] is 100% complete

[GUI (K15)] as [K15] lasts 3 days
[K15] is 0% complete

[Opret spil (K1)] as [K1] lasts 1 days
[K1] is 0% complete

[Indtast navn (k2)] as [K2] lasts 1 days
[K2] is 0% complete

[Vælg spillebrik (K3)] as [K3] lasts 1 days
[K3] is 0% complete



[Slå med terning (K4)] as [K4] lasts 1 days
[K4] is 0% complete

[Flyt brik (K5)] as [K5] lasts 1 days
[K5] is 0% complete



[Gå i fængsel (K13)] as [K13] lasts 1 days
[K13] is 0% complete

[Kom ud af fængsel (K14)] as [K14] lasts 1 days
[K14] is 0% complete

[Land på felt (K6)] as [K6] lasts 2 days
[K6] is 0% complete

[Træk changsekort (K18)] as [K18] lasts 1 days
[K18] is 0% complete

[Spiller penge (K7)] as [K7] lasts 1 days
[K7] is 0% complete

[Køb grund (K8)] as [K8] lasts 1 days
[K8] is 0% complete


[Betal leje (K9)] as [K9] lasts 1 days
[K9] is 0% complete

[Køb rederi (K11)] as [K11] lasts 1 days
[K11] is 0% complete

[Køb Bryggeri (K12)] as [K12] lasts 1 days
[K12] is 0% complete



[Penge over start (K10)] as [K10] lasts 1 days
[K10] is 0% complete




[Forlad spillet (K16)] as [K16] lasts 1 days
[K16] is 0% complete

[Vind spillet (K17)] as [K17] lasts 1 days
[K17] is 0% complete




[TASK1]-[#FF0000]->[TASK2]
[TASK2]->[K15]
[TASK2]->[K17]

[TASK2]-[#FF0000]->[K7]
[TASK2]-[#FF0000]->[K4]

[K15]->[K1]
[K15]->[K2]
[K15]->[K3]

[K4]->[K5]
[K4]-[#FF0000]->[K6]

[K7]->[K11]
[K6]->[K11]
[K7]->[K12]
[K6]->[K12]
[K7]->[K10]
[K6]->[K10]
[K7]-[#FF0000]->[K8]
[K6]-[#FF0000]->[K8]
[K6]->[K18]

[K7]->[K16]

[K8]-[#FF0000]->[K9]

[K5]->[K13]
[K5]->[K14]

@endgantt