@startuml
skinparam linetype ortho


class Language{
}

class GUIController{
 - gui: GUI
 - gui_players: GUI_Player
 + getPlayerName(String textOutput): String
 + getPlayerCharacter(String textOutput, String choices): String
 + updatePlayer(Player player)
 + updateProperty(Property property)
 + movePlayer(Player player)
 + getColorChoice(String text, String choices): String colorChoice
 + displayError(String errorText)
}
class GUIConverter{
 {static} + playersToGUI(Player[] player): GUI_Player[]
 {static} + fieldsToGUI(Field[] fields): GUI_Field[]
}
class GameController{
 - deck : Deck
 - turnCounter: int
 - isOver : boolean
 - currentPlayer : Player
 + takeTurn(Player)
 + takeChance() : boolean
 + CharacterSpecific(Player)
 + checkAllBalance(List<String>, Player[])
 + checkEqualBalance(List<String>, Player[])
 - landOnField(Player)
 - endGame()
 - findMaxBalance(Player[]) : String
 - findMaxTotalBalance(List<String>, Player[]) : String
}

class PlayerController{
 - players : Player[]
 + PlayerController(int)
 + addPlayer(String, String)
 + nameUnique(String): boolean
 + playerMove(Player, int)
 + payMoney(Player, int): boolean
 + getRent(Player, Property, boolean): boolean
 + getActivePlayer(int): Player
}

class FieldController{
 - fieldArrayList : ArrayList<Player>
 + generateGameFields(ArrayList<ArrayList<String>>)
 + playerProbertyValues() : HashMap<Player, int>
 + moveToColor(String) : int
 + jailPlayer(Player)
 + getFieldList() : ArrayList<Object>
}


class CSVReader{
 - DELIMITER : String
 - reader : BufferedReader
 - headers : String[]
 - file : String
 - fileAsArrayList : ArrayList<ArrayList<String>>
 + getData() : String[][]
 + getDataAsArrayList() : ArrayList<ArrayList<String>>
 + getHeaders() : String[]
 + getHeaderIndex(String) : int
 + toString() : String
}

class DiceHolder{
 - dice : Die[]
 - rolls : int[]
 + DiceHolder(int diceAmount)
 + roll()
 + getRolls() : int
 + sum() : int
}

GameController o-left- GUIController
GameController o-- PlayerController
GameController o-- FieldController
GameController o- DiceHolder
GameController o-- Language
GUIConverter --o GUIController
FieldController <. CSVReader

Language .> FieldController
Language .> GUIController

@enduml
