@startuml
skinparam linetype polyline
skinparam linetype ortho

Class Player {
 name
 balance
}

Class Field {
 name
}

Class ChanceCard{
 name
}
Class Die {
 faceValue
}


Player "3..6" -- "1" Game
Game "1" -- "45" ChanceCard
Game "1" -- "40" Field
Game"1" -- "2" Die
@enduml