@startgantt
printscale daily zoom 4
saturday are closed
sunday are closed

Project starts the 2nd of january 2023

[Skriv user stories] as [TASK1] lasts 1 days
[TASK1] is colored in Lavender/LightBlue
[TASK1] is 100% complete

[Skriv accept tests] as [TASK2] on {Asbjørn:25%} {Nilas:25%} {Phillip:25%} {Sandie:25%} lasts 1 days
[TASK2] is colored in Lavender/LightBlue
[TASK2] is 100% complete

[GUI (K15)] as [K15] lasts 3 days
[K15] is 100% complete

[Opret spil (K1)] as [K1] lasts 1 days
[K1] is 100% complete

[Indtast navn (k2)] as [K2] lasts 1 days
[K2] is 100% complete

[Vælg spillebrik (K3)] as [K3] lasts 1 days
[K3] is 100% complete



[Slå med terning (K4)] as [K4] lasts 1 days
[K4] is 100% complete

[Flyt brik (K5)] as [K5] lasts 1 days
[K5] is 100% complete



[Gå i fængsel (K13)] as [K13] lasts 1 days
[K13] is 100% complete

[Kom ud af fængsel (K14)] as [K14] lasts 1 days
[K14] is 100% complete

[Land på felt (K6)] as [K6] lasts 2 days
[K6] is 100% complete

[Træk changsekort (K18)] as [K18] lasts 1 days
[K18] is 100% complete

[Spiller penge (K7)] as [K7] lasts 1 days
[K7] is 100% complete

[Køb grund (K8)] as [K8] lasts 1 days
[K8] is 100% complete

[Betal leje (K9)] as [K9] lasts 1 days
[K9] is 100% complete

[Køb rederi (K11)] as [K11] lasts 1 days
[K11] is 100% complete

[Køb Bryggeri (K12)] as [K12] lasts 1 days
[K12] is 100% complete

[Penge over start (K10)] as [K10] lasts 1 days
[K10] is 100% complete

[Forlad spillet (K16)] as [K16] lasts 1 days
[K16] is 100% complete

[Vind spillet (K17)] as [K17] lasts 1 days
[K17] is 100% complete




[TASK1]-[#FF0000]->[TASK2]
[TASK2]->[K15]
[TASK2]->[K17]

[TASK2]-[#FF0000]->[K7]
[TASK2]-[#FF0000]->[K4]

[K15]->[K1]
[K15]->[K2]
[K15]->[K3]

[K4]->[K5]
[K4]-[#FF0000]->[K6]

[K7]->[K11]
[K6]->[K11]
[K7]->[K12]
[K6]->[K12]
[K7]->[K10]
[K6]->[K10]
[K7]-[#FF0000]->[K8]
[K6]-[#FF0000]->[K8]
[K6]->[K18]

[K7]->[K16]

[K8]-[#FF0000]->[K9]

[K5]->[K13]
[K5]->[K14]

[MVP completed] happens 2023-01-11

[MVP præsentation] as [MVP] starts 2023-01-11
[MVP] is colored in Lavender/LightBlue
[MVP] is 100% complete

[Ekstra tur (K19)] as [K19] lasts 1 days
[K19] is colored in Lavender/Yellow
[K19] is 100% complete

[Fængsel på 3. dobbeltslag (K31)] as [K31] starts 2023-01-16
[K31] is colored in Lavender/Teal
[K31] is 100% complete

[Land på felt, skat og afgift (K20)] as [K20] lasts 1 days
[K20] is colored in Lavender/Yellow
[K20] is 100% complete

[Changce kort, resten (K18)] as [K18.2] starts 2023-01-13
[Changce kort, resten (K18)] as [K18.2] ends 2023-01-16
[K18.2] is colored in Lavender/Orange
[K18.2] is 100% complete

[Leje bonus (K21)] as [K21] lasts 1 days
[K21] is colored in Lavender/Yellow
[K21] is 100% complete

[Købe huse (K22)] as [K22] lasts 2 days
[K22] is colored in Lavender/Yellow
[K22] is 100% complete

[købe sidste hus (K23)] as [K23] lasts 1 days
[K23] is colored in Lavender/Yellow
[K23] is 100% complete

[Køb hotel (K34)] as [K34] lasts 1 days
[K34] is colored in Lavender/Teal
[K34] is 100% complete

[Sælge huse (K26)] as [K26] lasts 1 days
[K26] is colored in Lavender/Orange
[K26] is 90% complete

[Spillet har 2 out-of-jail kort (K30)] as [K30] lasts 1 days
[K30] is colored in Lavender/Yellow
[K30] is 100% complete

[Bortaktioner grunde (K27)] as [K27] starts 2023-01-13
[Bortaktioner grunde (K27)] as [K27] ends 2023-01-16
[K27] is colored in Lavender/Teal
[K27] is 100% complete

[Ejendomspris i GUI (K32)] as [K32] starts 2023-01-16
[K32] is colored in Lavender/Teal
[K32] is 100% complete

[Ejer i GUI (K33)] as [K33] starts 2023-01-17
[K33] is colored in Lavender/Teal
[K33] is 100% complete

[Forbered acceptencetest] as [test] starts 2023-01-16
[Forbered acceptencetest] as [test] ends 2023-01-17
[test] is 75% complete

[MVP]->[K19]
[MVP]->[K20]
[MVP]-[#FF0000]->[K21]
[MVP]->[K30]
[MVP]->[K32]
[MVP]->[K33]
[MVP]->[K27]
[MVP]->[K18.2]
[MVP]->[test]

[K21]-[#FF0000]->[K22]
[K22]-[#FF0000]->[K23]
[K22]->[K34]
[K22]->[K26]

[K19]->[K31]

[Code freeze] happens 2023-01-18

[Aflever rapport] happens 2023-01-20
@endgantt