@startuml
'https://plantuml.com/class-diagram

abstract ChanceCard{
 # name : String
}

class Choice {

}

class MoveXSteps {
 - minSteps : int
 - maxSteps : int
}
class MoveToColor {
 - colorTargets : String[*]
}

class MoveToField {
 - fieldName : String
}

class CharacterSpecific {
 - character : Character
}

class ChangeBalance {
 - effect : int
}

class GetOutOfJail {

}

ChanceCard <|-- Choice
ChanceCard <|-- CharacterSpecific
ChanceCard <|-- ChangeBalance
ChanceCard <|-- GetOutOfJail
ChanceCard <|-- MoveXSteps
ChanceCard <|-- MoveToField
ChanceCard <|-- MoveToColor

@enduml